### PR TITLE
Fix namespace package

### LINKED ISSUE #89: Building docs and running tests is broken with namespace packages
The import in `conf.py` is wrong? Also tests don't run.

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Fixes #89

### CODE REVIEW

**Review by YooSunYoung — APPROVED** [review]

**Comment by YooSunYoung** [comment]
Oh.. it seems like `removeprefix` didn't work...?

**Comment by SimonHeybrock** [comment]
Yes, it needs Python 3.9. Oddly, it was already used by @jl-wynen in #44, not sure how that passed?

We can either move to 3.9, or try and find a different solution.

**Comment by YooSunYoung** [comment]
> Yes, it needs Python 3.9. Oddly, it was already used by @jl-wynen in #44, not sure how that passed?
> 
> We can either move to 3.9, or try and find a different solution.

I think it's because the default answers for testing don't use namespace package... 
Is it possible to have multiple python versions installed in the CI environment...?
then we can use copier with python 3.9 and test with python 3.8

**Comment by SimonHeybrock** [comment]
Or move CI to 3.9, since we plan to drop that in projects soon anyway?

**Comment by YooSunYoung** [comment]
> Or move CI to 3.9, since we plan to drop that in projects soon anyway?

I just opened the PR to do so in #91.

**Comment by SimonHeybrock** [comment]
I did it slightly different, to ensure that 3.8 still works for runtime.

**Pull request merged**
