### PR TITLE
Import scipp in doctest config

### PR DESCRIPTION
**Pull request by jl-wynen**
Basics copied from scipp but added try-except and modification of data group.

### CODE REVIEW

**Comment by YooSunYoung** [comment]
> Tests still failing because of failed dependency resolution

It works if `ipython` is limited to be below ``8.10.0``.
Should be temporarily pin `ipython` version...?

**Comment by jl-wynen** [comment]
> > Tests still failing because of failed dependency resolution
> 
> It works if `ipython` is limited to be below `8.10.0`. Should be temporarily pin `ipython` version...?

Can you do that in a separate PR?

**Comment by SimonHeybrock** [comment]
> > Tests still failing because of failed dependency resolution
> 
> It works if `ipython` is limited to be below `8.10.0`. Should be temporarily pin `ipython` version...?

Where do you add the pin? I am just trying and failing to run `tox -e deps` in `esssans`.

**Comment by jl-wynen** [comment]
> Where do you add the pin? I am just trying and failing to run tox -e deps in esssans.

Depends on what files causes the conflict. We put other pins into the files that resolved to a higher number.

**Comment by jl-wynen** [comment]
@SimonHeybrock Can you have another look?

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
