### PR TITLE
Add Code of conduct material in the jinja template.

### PR DESCRIPTION
**Pull request by YooSunYoung**
There was code of conduct of this template repository but the jinja template was blank...!

### CODE REVIEW

**Comment by nvaytet** [comment]
There is a non-jinja file already: https://github.com/scipp/copier_template/blob/main/CODE_OF_CONDUCT.md
I don't know if it means we don't need a template file, or if the blank template served a purpose?

**Comment by YooSunYoung** [comment]
I thought ``copier`` only copies ``jinja`` files, but ``requirements`` don't have any ``jinja`` files... hmm...
Maybe we can just delete this file since it is not using any of those variables set by copier....??

**Comment by SimonHeybrock** [comment]
Copier also copies non-jinja files. Since we COC for copier is the same as for other projects this should not be necessary. See https://scipp.github.io/sciline/developer/index.html#code-of-conduct where this works.

**Comment by SimonHeybrock** [comment]
Sorry, closed by accident: Yes, the empty file should be removed, I suppose?

**Comment by YooSunYoung** [comment]
I just removed the jinja file...! Thanks.

**Review by SimonHeybrock — APPROVED** [review]

**Pull request merged**
