### PR TITLE
Revert broken folder name change

### PR DESCRIPTION
**Pull request by SimonHeybrock**
Please review, but I'll merge so it can be tested.

### CODE REVIEW

**Review by jl-wynen — COMMENTED** [review]
Why is this broken? It seems to have worked in Plopp.

**Comment by SimonHeybrock** [comment]
I don't think Plopp is using copier_template yet?

**Comment by SimonHeybrock** [comment]
See here: https://github.com/scipp/esssans/actions/runs/6403759782

**Comment by jl-wynen** [comment]
But this change was done first in Plopp, then migrated to the template.
See https://github.com/scipp/plopp/blob/789dac62ce22932ec93a4dca9576711e7638fd4d/.github/workflows/docs.yml#L67
and correspondingly: https://github.com/scipp/plopp/blob/789dac62ce22932ec93a4dca9576711e7638fd4d/tox.ini#L27

**Comment by jl-wynen** [comment]
I don't care too much about the folder name. But `docs_html` is a little clearer. In particular because it gets placed in the root of the repo when using it locally.

**Comment by SimonHeybrock** [comment]
It is bad for tab completion :D

But we can of course change it to `html_docs` or something. But in that case this should be done properly, not as a side effect of an unrelated change. For example, it was "renamed" without updating the `.gitignore`. I don't know if other places are affected as well.

**Comment by SimonHeybrock** [comment]
> But this change was done first in Plopp, then migrated to the template. See https://github.com/scipp/plopp/blob/789dac62ce22932ec93a4dca9576711e7638fd4d/.github/workflows/docs.yml#L67 and correspondingly: https://github.com/scipp/plopp/blob/789dac62ce22932ec93a4dca9576711e7638fd4d/tox.ini#L27

Well, but it didn't work here, because #28 did not change the `tox.ini`.

**Pull request merged**
